name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build (and publish to NodePit when on master or release/*)
        run: |
          if [ -d $HOME/.m2 ]; then du -sh $HOME/.m2; fi

          # maven build
          mvn -V -B clean install

          # only use -P release when (1) on master branch, (2) no pull request
          # TODO move this into a separate action?!
          # TODO need to key!
          branch=${GITHUB_REF#refs/heads/}
          if [[ "$branch" =~ ^(master|release/.+)$ ]]; then 
            mkdir -p ~/.ssh &&
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config &&
            user_host=debian@nodepit.com &&
            label=${branch#release/} &&
            dest_directory=/home/debian/nodepit/download/files/jsondocgen/$label &&
            ssh-agent bash -c "ssh-add /tmp/ssh/nodepit && ssh $user_host 'mkdir -p $dest_directory' && scp -rp de.philippkatz.knime.jsondocgen.update/target/repository/* $user_host:$dest_directory";
          fi
