name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache .m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: 'm2-cache'

      - name: Build
        run: mvn -V -B clean install

      - name: Publish to NodePit
        # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')
        run: |
          branch=${GITHUB_REF#refs/heads/}
          label=${branch#release/}
          curl -s https://download.nodepit.com/developers/upload-update-site.sh |\
            bash -s -- $SFTP_USER $SFTP_PASSWORD $label
        env:
          SFTP_USER: jsondocgen
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
